//package com.nameless.social.core.entity;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//import lombok.AccessLevel;
//import lombok.Getter;
//import lombok.NoArgsConstructor;
//import lombok.Setter;
//
//@DynamoDBTable(tableName = "ChatMessage")
//@Getter
//@Setter
//@NoArgsConstructor(access = AccessLevel.PROTECTED)
//public class ChatMessage {
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
//	private String id;
//
//	@DynamoDBAttribute
//	private Long chatRoomId;
//
//	@DynamoDBAttribute
//	private Long senderId;
//
//	@DynamoDBAttribute
//	private String message;
//
//	// Constructor for Kafka deserialization
//	public ChatMessage(Long chatRoomId, Long senderId, String message) {
//		this.chatRoomId = chatRoomId;
//		this.senderId = senderId;
//		this.message = message;
//	}
//}